{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kotlin JVM used mem",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (jvm_memory_used_bytes) * 100) / sum by(instance) (jvm_memory_max_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB op counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{legacy_op_type!~\"update|command|query\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ktor request duration per route",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds_sum{route!=\"/metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}