version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    image: hubuspinovacao/frontend:${CURR_VERSION:-development}
    ports:
      - 3000:3000
    volumes:
      - nuxtdevdeps:/usr/src/app/node_modules
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      target: development
    image: hubuspinovacao/backend:${CURR_VERSION:-development}
    ports:
      - 3001:3000
    volumes:
      - railsdevdeps:/usr/src/app/vendor/bundle
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.1-bionic
    env_file:
      - ./backend/.env
    volumes:
      - data:/data/db

volumes:
  nuxtdevdeps:
  railsdevdeps:
  data:
