version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      target: production
    image: hubuspinovacao/backend:${CURR_VERSION:-production}
    ports:
      - 3001:3000
    volumes:
      - railsdeps:/usr/src/app/vendor/bundle
      - ./backend/log:/usr/src/app/log
      - ./backend/public/system:/usr/src/app/public/system
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.1-bionic
    env_file:
      - ./backend/.env
    volumes:
      - data:/data/db

volumes:
  railsdeps:
  data:
