version: '3.9'

services:
  app:
    build:
      context: .
      target: app
    ports:
      - 8080:8080
    env_file:
      - ./.env
    profiles:
      - app
      - all
    depends_on:
      - mongo

  cli:
    build:
      context: .
      target: cli
    env_file:
      - ./.env
    profiles:
      - cli
      - all
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.1-bionic
    ports:
      - 27017:27017
