name: cypress-CI

on:
  pull_request:

jobs:
  test:
    name: Test with Cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: run tests
        run: |
          cd frontend
          yarn run cypress-ci
