name: kotlin-CI
on:
  pull_request:
  push:
    branches: [master]

jobs:

  build:
    name: Kotlin build 
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: gradle build
        run: |
          cd server && ./gradlew build

