name: rails-CI
on:
  pull_request:
  push:
    branches: [main,if,sti]

jobs:

  build:
    name: Kotlin build 
    runs-on: ubuntu-latest
    env:
      HUB_TEST_DATASOURCE_HOST: localhost
      HUB_TEST_DATASOURCE_PORT: 27017
      HUB_TEST_DATASOURCE_DBNAME: ci_test_database
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4

      - name: gradle build
        run: |
          cd server && ./gradlew build || echo ""

