name: rails-CI
on:
  pull_request:
  push:
    branches: [main, if, sti]

jobs:

  linters:
    name: Ruby Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: backend/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          cd backend
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run linters
        run: |
          cd backend
          bundle exec rubocop --parallel

  tests:
    name: Ruby Tests
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: "supersecretforci"
      JWT_ISSUER: "https://github.com/hub-usp-inovacao/platform"

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: backend/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          cd backend
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Define Mongoid config
        run: mv backend/config/mongoid.ci.yml backend/config/mongoid.yml

      - name: Run tests
        run: |
          cd backend
          bundle exec rspec
